---
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: tekton-hub
type: Opaque
stringData:
  POSTGRESQL_DATABASE: tekton_hub
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_PORT: "5432"
